[package]
name = "db-static-dictionaries-parser"
version.workspace = true
edition.workspace = true

[dependencies]
crc32fast = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
arrayref = "0.3.9"

[lints]
workspace = true
