[package]
name = "login-server"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[features]
default = []

[dependencies]
openssl = { workspace = true }

foundation = { workspace = true }
